#!/bin/bash
# Refer https://github.com/rahul003/hudl/blob/master/README.md for detailed usage instructions
usage() {
  echo "Hudl - A bash utility to execute commands on a huddle of machines
Usage: 
  -h hostsfile 
     default=hosts
  -n number of hosts to read from hostsfile
  -i identityfile for ssh
  -t tmux mode
  -l log mode
  -p log prefix
  -v verbose mode
  -q run rsync in quiet mode for copying
  -c copy source path (ignores command given)
  -d copy destination path 
  -s script path
  -e echo most recent tmux log (ignores command given if any in this case)
  Refer https://github.com/rahul003/hudl/blob/master/README.md for detailed usage instructions"
}

error() {
  echo "Run '"hudl"' to see instructions on how to use this usage of this tool"
}

# adds tmux prefix if required
prepare_final_command() {
  command_arg=$1
  finalcommand=""
  if [ $echo_recent_log == true ]
  then
    finalcommand="pushd ./; cd ~/hudl/tmux_logs/ ; cat \`ls -t | head -n 1\` ; popd"
  elif [ $tmux_mode == true ]
  then
    if [ $log_mode == true ]
    then
      finalcommand="mkdir -p $log_dir && "
      LOG_FILE=$log_dir$log_prefix`date +%Y%m%d_%H%M%SZ`
      LOG_FILE+='.log'
      finalcommand+="tmux new-session -d \"$command_arg 2>&1 | tee -a $LOG_FILE\""
    else
      finalcommand+="tmux new-session -d \"$command_arg\""
    fi
  else
    finalcommand=$command_arg
  fi
}

parse_arguments() {
  tmux_mode=false
  log_mode=false
  quiet_mode=false
  log_dir='~/hudl/tmux_logs/'
  verbose_mode=false
  hosts_file="hosts"
  log_prefix=""
  dest_path=""
  echo_recent_log=false
  local OPTIND o t h c l v d s n i q p e
  while getopts "th:c:lvqd:s:n:i:p:e" o; do
    case "${o}" in
      t)
        tmux_mode=true
        ;;
      h)
        hosts_file=$OPTARG
        ;;
      c)
        copy_path=$OPTARG
        ;;
      d)
        dest_path=$OPTARG
        ;;
      l)
        log_mode=true
        ;;
      v)
        verbose_mode=true
        ;;
      s)
        script_path=$OPTARG
        ;;
      n)
        num_hosts=$OPTARG
        ;;
      i)
        identityfile=$OPTARG
        ;;
      q)
        quiet_mode=true
        ;;
      p)
	      log_prefix=$OPTARG
	      ;;
      e)
        echo_recent_log=true
        ;;
      \?)
        error
        return 1
        ;;
    esac
  done
  shift $(($OPTIND - 1))
  command=$@
}

hudl() {
  parse_arguments $@

  # if not running script mode or copy mode, command needs to be set
  if [ -z "$command" ] && [ -z "$script_path" ] && [ -z "$copy_path" ] && [ -z "$ccopy_path" ] && [ $echo_recent_log == false ]
  then
    usage
    return 0
  fi

  if [ $log_mode == true ] && [ $tmux_mode == false ]
  then
    echo "-l option only used with -t. Ignoring logging request"
  fi

  if [ -n "$copy_path" ] || [ -n "$script_path" ]
  then 
    if [ -n "$script_path" ]
    then
      copy_path=$script_path
      if [ -z "$dest_path" ]
      then
        dest_path='~/hudl/scripts/'
      else
        dest_path=${dest_path}/
      fi
    fi

    count=0
    while read -u 10 host;
    do
      host=${host%% slots*}
      if [[ -n "$num_hosts" && $count -ge $num_hosts ]]
      then
        break
      fi

      rsync_options="-az"
      if [[ $verbose_mode == true ]]
      then
        rsync_options+=" -v"
      fi
      if [[ $quiet_mode == true ]]
      then
        rsync_options+=" -q"
      fi
      copy_command='rsync '"$rsync_options"' '"$copy_path"' '"$host"':'"$dest_path"''
      prepare_final_command "$copy_command"
      if [ $verbose_mode == true ]
      then
        echo -e 'Copying to '$host'\n'$finalcommand
      fi
      eval $finalcommand
      let "count+=1"
    done 10<$hosts_file
    if [ -n "$script_path" ]
    then
      command="bash ${dest_path}$(basename $script_path) ${command}"
    fi
    if [ -n "$script_path" ]
    then
      unset copy_path
    fi
  fi

  if [ -n "$script_path" ] || [ -z "$copy_path" ]
  then
    prepare_final_command "$command"

    count=0
    while read -u 10 host;
    do
      host=${host%% slots*}
      if [[ -n "$num_hosts" && $count -ge $num_hosts ]]
      then
        break
      fi
      if [ $verbose_mode == true ]
      then
        echo -e "Running on ${host}:\n${finalcommand}"
      fi
      ssh -o "StrictHostKeyChecking no" $host $finalcommand ;
      let "count+=1"
    done 10<$hosts_file;
  fi
}

hudl $@
